[book]
authors = ["CompEng0001"]
language = "en"
multilingual = false
src = "src"
title = "Advanced Computer Engineering"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true


[output.html]
mathjax-support = true
input-404 = "404/404.md"


[output.html.print]
enable = false
